from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):

    def setUp(self):
        self.browser=webdriver.Firefox()

    def tearDown(self):
        self.browser.quit()
    
    def test_startAndRetrieveList(self):

        #Want to access app
        self.browser.get('http://127.0.0.1:8000')

        #has "Arnaud Meriguet" in the header
        self.assertIn ('Arnaud Meriguet', self.browser.title)
        self.fail("FINISH TEST")


        #in the CV page, the user enters an skill

        #types "Python" into a textbox

        #hits Enter, page updates, page has now a skill named "Python"

        #the box is still here waiting for more imputs
        #User inputs "Funtional testing"

        #page updates, both "python" and "Functional testing" can be seen on the CV

        #A URL has been generated by the site. 
        #Clicks on it, the CV remembers the inputs

if __name__=='__main__':
    unittest.main(warnings='ignore')