# Generated by Django 2.2.13 on 2020-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_skill_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('details', models.TextField(default='')),
            ],
        ),
    ]
