# Generated by Django 2.2.13 on 2020-06-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField()),
                ('title', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('months', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='year2',
            field=models.IntegerField(),
        ),
    ]
